import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { MapPin, Calendar, Camera, Star, Mountain, Sunset, Cloud, Thermometer, Zap, Navigation } from 'lucide-react';

// Inline stub for useJourneyTracker (module does not yet exist)
interface JourneyTimelineEvent {
  id?: string;
  type: string;
  state: string;
  date: string;
  current?: boolean;
  autoGenerated?: boolean;
  highlights: string[];
  weather?: { temperature: number };
  location?: { lat: number; lng: number };
}
interface JourneyWeather { temperature: number }
interface JourneyVehicleData {
  last_state?: {
    drive_state: { latitude?: number; longitude?: number; speed?: number };
    charge_state?: { battery_level?: number; charging_state?: string };
  };
}
function useJourneyTracker(): {
  timeline: JourneyTimelineEvent[];
  currentWeather: JourneyWeather | null;
  isLoading: boolean;
  vehicleData: JourneyVehicleData | null;
} {
  const [isLoading] = useState(false);
  return { timeline: [], currentWeather: null, isLoading, vehicleData: null };
}

const getTypeIcon = (type: string) => {
  switch (type) {
    case 'milestone': return Star;
    case 'scenic': return Mountain;
    case 'adventure': return Camera;
    case 'cultural': return Sunset;
    default: return MapPin;
  }
};

const getTypeColor = (type: string) => {
  switch (type) {
    case 'milestone': return 'text-[hsl(var(--adventure-gold))]';
    case 'scenic': return 'text-[hsl(var(--adventure-green))]';
    case 'adventure': return 'text-[hsl(var(--adventure-orange))]';
    case 'cultural': return 'text-[hsl(var(--adventure-purple))]';
    default: return 'text-primary';
  }
};

const JourneyTimeline = () => {
  const { timeline, currentWeather, isLoading, vehicleData } = useJourneyTracker();
  
  // Use live timeline data with better fallback handling
  const timelineEvents = timeline && timeline.length > 0 ? timeline : [];
  
  console.warn('JourneyTimeline render:', { 
    timelineLength: timeline?.length || 0, 
    isLoading, 
    hasCurrentWeather: !!currentWeather,
    hasVehicleData: !!vehicleData
  });
  
  // Show current vehicle status if available
  const currentLocation = vehicleData?.last_state ? 
    `${vehicleData.last_state.drive_state.latitude?.toFixed(4)}, ${vehicleData.last_state.drive_state.longitude?.toFixed(4)}` : 
    null;
  const batteryLevel = vehicleData?.last_state?.charge_state?.battery_level;
  const isCharging = vehicleData?.last_state?.charge_state?.charging_state === 'Charging';
  
  if (isLoading && timelineEvents.length === 0) {
    return (
      <Card className="story-card">
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-gradient">
            <Calendar className="w-5 h-5" />
            Journey Chronicles
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="flex items-center justify-center p-8">
            <div className="text-center">
              <div className="w-8 h-8 border-2 border-primary border-t-transparent rounded-full animate-spin mx-auto mb-4"></div>
              <p className="text-muted-foreground">Loading journey timeline...</p>
            </div>
          </div>
        </CardContent>
      </Card>
    );
  }

  if (timelineEvents.length === 0) {
    return (
      <Card className="story-card">
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-gradient">
            <Calendar className="w-5 h-5" />
            Journey Chronicles
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="flex items-center justify-center p-8">
            <div className="text-center">
              <Calendar className="w-12 h-12 mx-auto mb-4 text-muted-foreground" />
              <p className="text-lg font-semibold mb-2">No Timeline Data</p>
              <p className="text-sm text-muted-foreground">
                Timeline will populate when vehicle data is available or you can import historical data.
              </p>
            </div>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card className="story-card">
      <CardHeader>
        <CardTitle className="flex items-center gap-2 text-gradient">
          <Calendar className="w-5 h-5" />
          Journey Chronicles
          <Badge className="ml-auto bg-[hsl(var(--tesla-blue)/0.2)] text-[hsl(var(--tesla-blue))]">
            {timelineEvents.length} Events
          </Badge>
          {currentLocation && (
            <Badge className="bg-[hsl(var(--adventure-orange)/0.2)] text-[hsl(var(--adventure-orange))]">
              <Navigation className="w-3 h-3 mr-1" />
              Live GPS
            </Badge>
          )}
          {batteryLevel && (
            <Badge className={`${isCharging ? 'bg-[hsl(var(--adventure-green)/0.2)] text-[hsl(var(--adventure-green))]' : 'bg-[hsl(var(--tesla-blue)/0.2)] text-[hsl(var(--tesla-blue))]'}`}>
              <Zap className="w-3 h-3 mr-1" />
              {batteryLevel}% {isCharging ? '⚡' : '🔋'}
            </Badge>
          )}
          {currentWeather && (
            <Badge className="bg-[hsl(var(--tesla-blue)/0.2)] text-[hsl(var(--tesla-blue))]">
              <Thermometer className="w-3 h-3 mr-1" />
              {Math.round(currentWeather.temperature)}°F
            </Badge>
          )}
        </CardTitle>
      </CardHeader>
      <CardContent>
        {/* Live Vehicle Status */}
        {currentLocation && (
          <div className="mb-6 p-4 bg-[hsl(var(--adventure-orange)/0.1)] rounded-lg border border-[hsl(var(--adventure-orange)/0.2)]">
            <h4 className="font-semibold text-[hsl(var(--adventure-orange))] mb-2 flex items-center gap-2">
              <Navigation className="w-4 h-4" />
              Live Vehicle Status
            </h4>
            <div className="grid grid-cols-2 gap-4 text-sm">
              <div>
                <span className="text-muted-foreground">Location: </span>
                <span className="font-mono">{currentLocation}</span>
              </div>
              <div>
                <span className="text-muted-foreground">Battery: </span>
                <span className={batteryLevel && batteryLevel < 30 ? 'text-[hsl(var(--destructive))]' : 'text-foreground'}>
                  {batteryLevel}% {isCharging ? '(Charging)' : ''}
                </span>
              </div>
              <div>
                <span className="text-muted-foreground">Status: </span>
                <span className="text-foreground">
                  {(vehicleData?.last_state?.drive_state?.speed ?? 0) > 0 ? 'Moving' : 'Parked'}
                </span>
              </div>
              <div>
                <span className="text-muted-foreground">Last Update: </span>
                <span className="text-foreground">
                  {new Date().toLocaleTimeString()}
                </span>
              </div>
            </div>
          </div>
        )}

        <div className="relative">
          {/* Timeline line */}
          <div className="absolute left-6 top-4 bottom-4 w-0.5 bg-gradient-to-b from-[hsl(var(--tesla-blue))] via-[hsl(var(--adventure-orange))] to-[hsl(var(--tesla-gray))]" />
          
          <div className="space-y-6">
            {timelineEvents.map((event, index) => {
              const IconComponent = getTypeIcon(event.type);
              const iconColor = getTypeColor(event.type);
              
              const isCurrent = event.current || (event.autoGenerated && event.highlights?.some(h => h.includes('Current location')));
              const isAutoGenerated = event.autoGenerated;
              const isWeatherAvailable = event.weather;
              
              return (
                <div key={event.id || index} className="relative flex gap-4">
                  {/* Timeline dot */}
                  <div className={`relative z-10 flex items-center justify-center w-12 h-12 rounded-full ${
                    isCurrent ? 'bg-[hsl(var(--adventure-orange))] animate-pulse' : 
                    isAutoGenerated ? 'bg-[hsl(var(--tesla-cyan))]' :
                    'bg-[hsl(var(--tesla-gray-light))]'
                  } border-2 border-background`}>
                    <IconComponent className={`w-5 h-5 ${
                      isCurrent ? 'text-white' : 
                      isAutoGenerated ? 'text-white' : 
                      iconColor
                    }`} />
                  </div>
                  
                  {/* Event content */}
                  <div className="flex-1 pb-6">
                    <div className="flex items-center gap-3 mb-2 flex-wrap">
                      <h3 className="font-bold text-lg">{event.state}</h3>
                      {isCurrent && (
                        <Badge className="bg-[hsl(var(--adventure-orange))] text-white text-xs">
                          Current Location
                        </Badge>
                      )}
                      {isAutoGenerated && (
                        <Badge className="bg-[hsl(var(--tesla-cyan)/0.2)] text-[hsl(var(--tesla-cyan))] text-xs">
                          🤖 Live Data
                        </Badge>
                      )}
                      {!isAutoGenerated && (
                        <Badge className="bg-[hsl(var(--tesla-blue)/0.2)] text-[hsl(var(--tesla-blue))] text-xs">
                          📋 Journey Log
                        </Badge>
                      )}
                    </div>
                    
                    <div className="flex items-center gap-4 mb-3 flex-wrap">
                      <p className="text-sm text-muted-foreground">{new Date(event.date).toLocaleDateString()}</p>
                      {isWeatherAvailable && (
                        <div className="flex items-center gap-2 text-xs">
                          <Cloud className="w-3 h-3 text-[hsl(var(--tesla-blue))]" />
                          <span className="text-[hsl(var(--tesla-blue))]">
                            {Math.round(isWeatherAvailable.temperature)}°F
                          </span>
                        </div>
                      )}
                      {event.location && (
                        <div className="flex items-center gap-2 text-xs">
                          <MapPin className="w-3 h-3 text-[hsl(var(--tesla-gray))]" />
                          <span className="text-muted-foreground font-mono">
                            {event.location.lat.toFixed(3)}, {event.location.lng.toFixed(3)}
                          </span>
                        </div>
                      )}
                    </div>
                    
                    <div className="space-y-2">
                      {event.highlights.map((highlight, idx) => (
                        <div key={idx} className="flex items-start gap-2">
                          <div className="w-1.5 h-1.5 bg-[hsl(var(--adventure-gold))] rounded-full mt-2" />
                          <span className={`text-sm ${
                            highlight.includes('🤖') || highlight.includes('GPS:') ? 
                            'text-[hsl(var(--tesla-cyan))] font-mono text-xs' : 
                            'text-foreground/80'
                          }`}>
                            {highlight}
                          </span>
                        </div>
                      ))}
                    </div>
                    
                    {/* Extended stay display */}
                    {event.highlights.some(h => h.includes('Extended stay')) && (
                      <div className="mt-2 text-xs text-[hsl(var(--adventure-green))] bg-[hsl(var(--adventure-green)/0.1)] px-2 py-1 rounded">
                        {event.highlights.find(h => h.includes('Extended stay'))}
                      </div>
                    )}
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </CardContent>
    </Card>
  );
};

export default JourneyTimeline;