import React, { useState } from 'react';
import {
  Plus,
  MapPin,
  Calendar,
  Camera,
  Edit3,
  Trash2,
  Brain,
  Zap,
  TrendingUp,
  Battery,
  MessageSquare,
} from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { backendApi } from '@/services/backendApi';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';

interface JournalEntry {
  id: number;
  title: string;
  content: string;
  location: string;
  timestamp: string;
  type: string;
  autoGenerated: boolean;
  photos?: string[];
  vehicleStats?: {
    battery: number;
    range: number;
    efficiency?: number;
  };
  mood?: string;
}

interface CurrentLocation {
  latitude: number;
  longitude: number;
}

interface JourneyJournalProps {
  entries?: JournalEntry[];
  onAddEntry?: (entry: JournalEntry) => void;
  currentLocation?: CurrentLocation;
  isAutoGenerating?: boolean;
  onGenerateEntry?: (type: string) => void;
}

export default function JourneyJournal({
  entries: propEntries,
  onAddEntry,
  currentLocation,
  isAutoGenerating,
  onGenerateEntry,
}: JourneyJournalProps) {
  const [entries, setEntries] = useState<JournalEntry[]>(propEntries || []);
  const [isAddingEntry, setIsAddingEntry] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [newEntry, setNewEntry] = useState<Partial<JournalEntry>>({
    title: '',
    content: '',
    mood: 'neutral',
    location: '',
    autoGenerated: false,
  });

  // AI generation function using backend API
  const handleAIGeneration = async (type: string) => {
    setIsGenerating(true);
    try {
      const today = new Date().toISOString().split('T')[0];
      const location = 'Current Tesla location'; // Could be enhanced with real location

      const response = await backendApi.generateJournal({
        date: today,
        location,
        events: [type]
      });

      if (response.success && response.entry) {
        const aiEntry: JournalEntry = {
          id: Date.now(),
          title: `AI Generated: ${type.replace('_', ' ')}`,
          content: response.entry.content,
          location: response.entry.location || location,
          timestamp: new Date().toISOString(),
          type: type,
          autoGenerated: true,
          vehicleStats: response.entry.metadata ? {
            battery: 85,
            range: 250,
            efficiency: response.entry.metadata.recentEfficiency || 3.5
          } : undefined,
          mood: 'excited'
        };

        setEntries(prev => [aiEntry, ...prev]);
      } else {
        throw new Error('AI generation failed');
      }
    } catch (error) {
      console.error('AI generation error:', error);
      // Fallback to prop function if available
      if (onGenerateEntry) {
        onGenerateEntry(type);
      }
    } finally {
      setIsGenerating(false);
    }
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newEntry.title?.trim() || !newEntry.content?.trim()) return;

    const entry: JournalEntry = {
      id: Date.now(),
      title: newEntry.title || '',
      content: newEntry.content || '',
      timestamp: new Date().toISOString(),
      type: 'manual',
      autoGenerated: false,
      mood: newEntry.mood,
      photos: newEntry.photos,
      location:
        newEntry.location ||
        (currentLocation
          ? `${currentLocation.latitude.toFixed(4)}, ${currentLocation.longitude.toFixed(4)}`
          : 'Unknown Location'),
    };

    onAddEntry?.(entry);
    setNewEntry({ title: '', content: '', location: '', photos: [] });
    setIsAddingEntry(false);
  };

  const formatDate = (timestamp: string) => {
    return new Date(timestamp).toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  };

  const getEntryIcon = (entry: JournalEntry) => {
    if (entry.autoGenerated) {
      switch (entry.type) {
        case 'charging_started':
        case 'charging_completed':
          return <Zap className="h-4 w-4 text-green-600" />;
        case 'location_change':
          return <MapPin className="h-4 w-4 text-blue-600" />;
        case 'efficiency_milestone':
          return <TrendingUp className="h-4 w-4 text-purple-600" />;
        case 'low_battery_warning':
          return <Battery className="h-4 w-4 text-red-600" />;
        default:
          return <Brain className="h-4 w-4 text-purple-600" />;
      }
    }
    return <MessageSquare className="h-4 w-4 text-muted-foreground" />;
  };

  const quickTemplates = [
    'Charging stop',
    'Scenic view',
    'Food break',
    'Rest stop',
    'Milestone reached',
    'Great efficiency!',
  ];

  return (
    <Card className="h-96 flex flex-col">
      {/* Enhanced Header with AI Status */}
      <CardHeader className="pb-3">
        <div className="flex items-center justify-between mb-3">
          <CardTitle className="flex items-center gap-2">
            <Edit3 className="w-5 h-5" />
            Journey Journal
          </CardTitle>
          {isAutoGenerating && (
            <div className="flex items-center gap-2 text-sm text-purple-600">
              <Brain className="w-4 h-4 animate-pulse" />
              <span>AI writing entry...</span>
            </div>
          )}
          <Button
            size="sm"
            onClick={() => setIsAddingEntry(true)}
            className="gap-2"
          >
            <Plus className="w-4 h-4" />
            Add Entry
          </Button>
        </div>

        {/* AI Generation Buttons */}
        <div className="flex items-center gap-2 mb-3">
          <span className="text-xs text-muted-foreground">AI Generate:</span>
          <Button
            variant="outline"
            size="sm"
            onClick={() => handleAIGeneration('location_change')}
            disabled={isGenerating}
            className="h-6 px-2 text-xs"
          >
            <MapPin className="w-3 h-3 mr-1" />
            {isGenerating ? 'Generating...' : 'Location Update'}
          </Button>
          <Button
            variant="outline"
            size="sm"
            onClick={() => handleAIGeneration('efficiency_milestone')}
            disabled={isGenerating}
            className="h-6 px-2 text-xs"
          >
            <TrendingUp className="w-3 h-3 mr-1" />
            {isGenerating ? 'Generating...' : 'Efficiency Milestone'}
          </Button>
          <Button
            variant="outline"
            size="sm"
            onClick={() => handleAIGeneration('charging_experience')}
            disabled={isGenerating}
            className="h-6 px-2 text-xs"
          >
            <Battery className="w-3 h-3 mr-1" />
            {isGenerating ? 'Generating...' : 'Charging Stop'}
          </Button>
        </div>
      </CardHeader>

      <CardContent className="flex-1 overflow-hidden flex flex-col p-0">
        {/* Add Entry Form */}
        {isAddingEntry && (
          <div className="p-4 border-b bg-muted/30">
            <form onSubmit={handleSubmit} className="space-y-3">
              <Input
                placeholder="Entry title..."
                value={newEntry.title}
                onChange={(e) =>
                  setNewEntry((prev) => ({ ...prev, title: e.target.value }))
                }
                autoFocus
              />
              <Textarea
                placeholder="What happened on your journey?"
                value={newEntry.content}
                onChange={(e) =>
                  setNewEntry((prev) => ({ ...prev, content: e.target.value }))
                }
                rows={3}
                className="resize-none"
              />
              <Input
                placeholder="Location (optional)"
                value={newEntry.location}
                onChange={(e) =>
                  setNewEntry((prev) => ({ ...prev, location: e.target.value }))
                }
              />
              <div className="flex gap-2">
                <Button type="submit" className="flex-1">
                  Save Entry
                </Button>
                <Button
                  type="button"
                  variant="outline"
                  onClick={() => {
                    setIsAddingEntry(false);
                    setNewEntry({
                      title: '',
                      content: '',
                      location: '',
                      photos: [],
                    });
                  }}
                >
                  Cancel
                </Button>
              </div>
            </form>
          </div>
        )}

        {/* Entries List */}
        <div className="flex-1 overflow-y-auto">
          {entries.length === 0 ? (
            <div className="p-8 text-center text-muted-foreground">
              <div className="flex justify-center gap-2 mb-4">
                <Edit3 className="w-8 h-8 text-muted-foreground/50" />
                <Brain className="w-8 h-8 text-purple-300" />
              </div>
              <p className="text-sm">No journal entries yet.</p>
              <p className="text-xs text-muted-foreground mt-1">
                AI will automatically create entries as you drive, or add your own!
              </p>
            </div>
          ) : (
            <div className="p-4 space-y-4">
              {entries.map((entry) => (
                <div
                  key={entry.id}
                  className={`border rounded-lg p-4 shadow-sm transition-all hover:shadow-md ${
                    entry.autoGenerated
                      ? 'bg-gradient-to-r from-purple-50 to-blue-50 border-purple-200'
                      : 'bg-card border-border'
                  }`}
                >
                  <div className="flex items-start justify-between mb-2">
                    <div className="flex items-center gap-2 flex-1">
                      {getEntryIcon(entry)}
                      <h4 className="font-semibold text-foreground text-sm">
                        {entry.title}
                      </h4>
                      {entry.autoGenerated && (
                        <Badge variant="secondary" className="text-xs">
                          <Brain className="w-2.5 h-2.5 mr-1" />
                          AI
                        </Badge>
                      )}
                    </div>
                    <div className="flex items-center gap-1">
                      <Button variant="ghost" size="sm" className="h-6 w-6 p-0">
                        <Edit3 className="w-3 h-3" />
                      </Button>
                      <Button variant="ghost" size="sm" className="h-6 w-6 p-0 text-destructive">
                        <Trash2 className="w-3 h-3" />
                      </Button>
                    </div>
                  </div>

                  <p className="text-sm text-muted-foreground mb-3 leading-relaxed">
                    {entry.content}
                  </p>

                  <div className="flex items-center justify-between text-xs text-muted-foreground">
                    <div className="flex items-center gap-4">
                      <div className="flex items-center gap-1">
                        <Calendar className="w-3 h-3" />
                        <span>{formatDate(entry.timestamp)}</span>
                      </div>
                      {entry.location && (
                        <div className="flex items-center gap-1">
                          <MapPin className="w-3 h-3" />
                          <span className="truncate max-w-24">
                            {typeof entry.location === 'string'
                              ? entry.location
                              : entry.location}
                          </span>
                        </div>
                      )}
                      {entry.vehicleStats && (
                        <div className="flex items-center gap-1">
                          <Battery className="w-3 h-3" />
                          <span>{entry.vehicleStats.battery}%</span>
                        </div>
                      )}
                    </div>
                    <div className="flex items-center gap-2">
                      {entry.photos && entry.photos.length > 0 && (
                        <div className="flex items-center gap-1">
                          <Camera className="w-3 h-3" />
                          <span>{entry.photos.length}</span>
                        </div>
                      )}
                      {entry.mood && (
                        <span className="text-xs">
                          {entry.mood === 'excited' && '🚗'}
                          {entry.mood === 'happy' && '😊'}
                          {entry.mood === 'satisfied' && '👍'}
                          {entry.mood === 'neutral' && '📝'}
                          {entry.mood === 'concerned' && '😐'}
                          {entry.mood === 'frustrated' && '😤'}
                        </span>
                      )}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Enhanced Quick Entry Templates */}
        <div className="p-4 border-t bg-muted/30">
          <p className="text-xs text-muted-foreground mb-2">Quick entries:</p>
          <div className="flex flex-wrap gap-1">
            {quickTemplates.map((template) => (
              <Button
                key={template}
                variant="outline"
                size="sm"
                className="h-6 px-2 text-xs"
                onClick={() => {
                  setNewEntry((prev) => ({
                    ...prev,
                    title: template,
                    content: `${template} at ${
                      currentLocation
                        ? `${currentLocation.latitude.toFixed(4)}, ${currentLocation.longitude.toFixed(4)}`
                        : 'current location'
                    }`,
                  }));
                  setIsAddingEntry(true);
                }}
              >
                {template}
              </Button>
            ))}
          </div>
        </div>
      </CardContent>
    </Card>
  );
}
