import React, { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Button } from '@/components/ui/button';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { MapPin, Calendar, Clock, Trophy, Camera, PenTool, Target, Route, Zap, Upload, Map as MapIcon, Cloud } from 'lucide-react';
// SecureDataImport removed for production security
import { journeyTimeline, journeyStats, routeLocations as staticRouteLocations } from '@/data/journeyData';
import { useJourneyTracker } from '@/hooks/useJourneyTracker';
import AdventureHero from './AdventureHero';
import JourneyTimeline from './JourneyTimeline';
import AdventureMilestones from './AdventureMilestones';
import LazyTeslaMap from './LazyTeslaMap';
import { calculateTripStatistics } from '@/utils/stateDetection';

const RoadTripTracker = () => {
  const [importedData, setImportedData] = useState<any[]>([]);
  const [mapboxToken, setMapboxToken] = useState<string>(() => 
    localStorage.getItem('mapboxToken') || ''
  );
  const [tripStatistics, setTripStatistics] = useState(journeyStats);
  const [routeLocations, setRouteLocations] = useState<Array<{lat: number, lng: number, timestamp: string}>>(staticRouteLocations);
  const [isAdminMode, setIsAdminMode] = useState(false);
  
  // Use live journey data
  const { 
    timeline, 
    journeyStats: liveStats, 
    currentWeather, 
    weatherLoading, 
    vehicleData,
    isLoading 
  } = useJourneyTracker();
  
  // Use live data if available, fallback to static data
  const currentJourneyStats = timeline.length > 0 ? liveStats : tripStatistics;
  const visitedStates = timeline.length > 0 ? timeline.filter(e => e.autoGenerated) : journeyTimeline.filter(state => state.current);
  const currentState = timeline.length > 0 ? timeline.find(e => e.autoGenerated && e.highlights.some(h => h.includes('Current location'))) : journeyTimeline.find(state => state.current);
  const progressPercentage = (currentJourneyStats.visitedStates / currentJourneyStats.totalStates) * 100;

  const handleDataImport = (data: any[]) => {
    setImportedData(data);
    
    // Calculate real trip statistics from imported data
    const stats = calculateTripStatistics(data);
    setTripStatistics({
      totalStates: 48,
      visitedStates: stats.statesDetected.length,
      remainingStates: 48 - stats.statesDetected.length,
      tripDuration: 55,
      daysElapsed: stats.daysElapsed,
      daysRemaining: null,
      startDate: '2025-06-01',
      currentDate: '2025-07-26',
      currentState: 'Connecticut',
      totalMiles: stats.totalMiles || 8500,
      averageMilesPerDay: stats.averageMilesPerDay || 154,
      completionPercentage: Math.round((stats.statesDetected.length / 48) * 100)
    });
  };

  const handleMapDataAvailable = (locations: Array<{lat: number, lng: number, timestamp: string}>) => {
    setRouteLocations(locations);
  };

  const handleTokenChange = (token: string) => {
    setMapboxToken(token);
    localStorage.setItem('mapboxToken', token);
  };

  return (
    <div className="space-y-8">
      {/* Adventure Tabs */}
      <Tabs defaultValue="overview" className="space-y-6">
        <TabsList className="grid w-full grid-cols-5 bg-[hsl(var(--tesla-gray))]">
          <TabsTrigger value="overview" className="data-[state=active]:bg-[hsl(var(--adventure-orange))] data-[state=active]:text-white">
            <MapIcon className="w-4 h-4 mr-2" />
            Adventure Overview
          </TabsTrigger>
          <TabsTrigger value="map" className="data-[state=active]:bg-[hsl(var(--adventure-orange))] data-[state=active]:text-white">
            <Route className="w-4 h-4 mr-2" />
            Route Map
          </TabsTrigger>
          <TabsTrigger value="timeline" className="data-[state=active]:bg-[hsl(var(--adventure-orange))] data-[state=active]:text-white">
            <Clock className="w-4 h-4 mr-2" />
            Journey Timeline
          </TabsTrigger>
          <TabsTrigger value="achievements" className="data-[state=active]:bg-[hsl(var(--adventure-orange))] data-[state=active]:text-white">
            <Trophy className="w-4 h-4 mr-2" />
            Achievements
          </TabsTrigger>
          <TabsTrigger value="import" className="data-[state=active]:bg-[hsl(var(--adventure-orange))] data-[state=active]:text-white">
            <Upload className="w-4 h-4 mr-2" />
            Import Data
          </TabsTrigger>
        </TabsList>

        <TabsContent value="overview" className="space-y-8">
          {/* Hero Section */}
          <AdventureHero
            currentLocation={currentState?.state || currentJourneyStats.currentState}
            daysElapsed={currentJourneyStats.daysElapsed}
            totalDays={currentJourneyStats.daysElapsed}
            statesVisited={currentJourneyStats.visitedStates}
            totalStates={currentJourneyStats.totalStates}
          />
          
          {/* Weather Integration Display */}
          {currentWeather && (
            <Card className="story-card bg-gradient-to-r from-[hsl(var(--tesla-blue)/0.1)] to-[hsl(var(--tesla-cyan)/0.1)]">
              <CardContent className="p-6">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-4">
                    <div className="p-3 bg-[hsl(var(--tesla-blue)/0.2)] rounded-xl">
                      <Cloud className="w-8 h-8 text-[hsl(var(--tesla-blue))]" />
                    </div>
                    <div>
                      <h3 className="text-lg font-bold">Current Weather</h3>
                      <p className="text-sm text-muted-foreground">
                        {currentWeather.weather[0]?.description || 'Clear skies'}
                      </p>
                    </div>
                  </div>
                  <div className="text-right">
                    <div className="text-3xl font-bold text-[hsl(var(--tesla-blue))]">
                      {Math.round(currentWeather.temperature)}°F
                    </div>
                    <div className="text-sm text-muted-foreground">
                      Feels like {Math.round(currentWeather.feels_like)}°F
                    </div>
                  </div>
                </div>
                <div className="grid grid-cols-3 gap-4 mt-4 pt-4 border-t border-[hsl(var(--tesla-gray-light))]">
                  <div className="text-center">
                    <div className="text-lg font-semibold">{currentWeather.humidity}%</div>
                    <div className="text-xs text-muted-foreground">Humidity</div>
                  </div>
                  <div className="text-center">
                    <div className="text-lg font-semibold">{Math.round(currentWeather.wind.speed)} mph</div>
                    <div className="text-xs text-muted-foreground">Wind Speed</div>
                  </div>
                  <div className="text-center">
                    <div className="text-lg font-semibold">{Math.round(currentWeather.visibility / 1000)} mi</div>
                    <div className="text-xs text-muted-foreground">Visibility</div>
                  </div>
                </div>
              </CardContent>
            </Card>
          )}

          {/* Key Adventure Statistics */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
            <Card className="story-card group">
              <CardContent className="p-6">
                <div className="flex items-center gap-4">
                  <div className="p-3 bg-gradient-to-br from-[hsl(var(--adventure-gold)/0.2)] to-[hsl(var(--adventure-orange)/0.1)] rounded-xl">
                    <Trophy className="w-6 h-6 text-[hsl(var(--adventure-gold))]" />
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground font-medium">Epic Milestones</p>
                    <p className="text-2xl font-bold text-gradient">{currentJourneyStats.visitedStates} States</p>
                    <p className="text-xs text-muted-foreground">of {currentJourneyStats.totalStates} planned</p>
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card className="story-card group">
              <CardContent className="p-6">
                <div className="flex items-center gap-4">
                  <div className="p-3 bg-gradient-to-br from-[hsl(var(--tesla-cyan)/0.2)] to-[hsl(var(--tesla-blue)/0.1)] rounded-xl">
                    <Clock className="w-6 h-6 text-[hsl(var(--tesla-cyan))]" />
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground font-medium">Adventure Days</p>
                    <p className="text-2xl font-bold text-[hsl(var(--tesla-cyan))]">{currentJourneyStats.daysElapsed}</p>
                    <p className="text-xs text-muted-foreground">days on the road</p>
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card className="story-card group">
              <CardContent className="p-6">
                <div className="flex items-center gap-4">
                  <div className="p-3 bg-gradient-to-br from-[hsl(var(--adventure-orange)/0.2)] to-[hsl(var(--adventure-red)/0.1)] rounded-xl">
                    <Route className="w-6 h-6 text-[hsl(var(--adventure-orange))]" />
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground font-medium">Miles Conquered</p>
                    <p className="text-2xl font-bold text-[hsl(var(--adventure-orange))]">{(currentJourneyStats.totalMiles / 1000).toFixed(1)}K</p>
                    <p className="text-xs text-muted-foreground">and counting...</p>
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card className="story-card group">
              <CardContent className="p-6">
                <div className="flex items-center gap-4">
                  <div className="p-3 bg-gradient-to-br from-[hsl(var(--adventure-green)/0.2)] to-[hsl(var(--adventure-teal)/0.1)] rounded-xl">
                    <Zap className="w-6 h-6 text-[hsl(var(--adventure-green))]" />
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground font-medium">Daily Average</p>
                    <p className="text-2xl font-bold text-[hsl(var(--adventure-green))]">{currentJourneyStats.averageMilesPerDay}</p>
                    <p className="text-xs text-muted-foreground">miles per day</p>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>

          {/* Epic Journey Progress */}
          <Card className="story-card relative overflow-hidden">
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-gradient">
                <MapPin className="w-5 h-5" />
                Epic Journey Progress
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="space-y-4">
                <div className="flex justify-between items-center">
                  <span className="text-lg font-medium">Adventure Completion</span>
                  <div className="text-right">
                    <span className="text-3xl font-bold text-gradient">{progressPercentage.toFixed(1)}%</span>
                    <p className="text-xs text-muted-foreground">of America explored</p>
                  </div>
                </div>
                
                <div className="journey-progress h-4 rounded-full">
                  <div 
                    className="progress-fill h-full rounded-full transition-all duration-1000 ease-out"
                    style={{ width: `${progressPercentage}%` }}
                  />
                </div>
                
                <div className="grid grid-cols-3 gap-4 text-center">
                  <div>
                    <div className="text-2xl font-bold text-[hsl(var(--adventure-green))]">{currentJourneyStats.visitedStates}</div>
                    <div className="text-xs text-muted-foreground">States Conquered</div>
                  </div>
                  <div>
                    <div className="text-2xl font-bold text-[hsl(var(--adventure-orange))]">{currentJourneyStats.daysElapsed}</div>
                    <div className="text-xs text-muted-foreground">Days of Adventure</div>
                  </div>
                  <div>
                    <div className="text-2xl font-bold text-[hsl(var(--tesla-cyan))]">{currentJourneyStats.totalStates - currentJourneyStats.visitedStates}</div>
                    <div className="text-xs text-muted-foreground">States Awaiting</div>
                  </div>
                </div>
              </div>
              
              {currentState && (
                <div className="pt-4 border-t border-[hsl(var(--tesla-gray-light))]">
                  <div className="flex items-center gap-3">
                    <Badge className="bg-[hsl(var(--adventure-orange))] text-white px-3 py-1 animate-pulse">
                      📍 Currently Exploring
                    </Badge>
                    <span className="font-semibold text-lg">{currentState.state}</span>
                  </div>
                  <div className="mt-2 flex flex-wrap gap-2">
                    {currentState.highlights.map((highlight, idx) => (
                      <span key={idx} className="text-sm text-muted-foreground bg-[hsl(var(--tesla-gray))] px-2 py-1 rounded">
                        {highlight}
                      </span>
                    ))}
                  </div>
                </div>
              )}
            </CardContent>
            
            {/* Background decoration */}
            <div className="absolute top-0 right-0 w-32 h-32 bg-[hsl(var(--adventure-gold))] opacity-5 rounded-full blur-3xl animate-pulse" />
          </Card>

          {/* States Adventure Log */}
          <Card className="story-card">
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-gradient">
                <Calendar className="w-5 h-5" />
                Adventure Log: States Conquered
              </CardTitle>
            </CardHeader>
            <CardContent>
              <Table>
                <TableHeader>
                  <TableRow className="border-[hsl(var(--tesla-gray-light))]">
                    <TableHead className="text-muted-foreground font-semibold">State</TableHead>
                    <TableHead className="text-muted-foreground font-semibold">Adventure Status</TableHead>
                    <TableHead className="text-muted-foreground font-semibold">Date Conquered</TableHead>
                    <TableHead className="text-muted-foreground font-semibold">Epic Stops</TableHead>
                    <TableHead className="text-muted-foreground font-semibold">Memories</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {journeyTimeline.map((state) => (
                    <TableRow key={state.state} className="border-[hsl(var(--tesla-gray-light))] hover:bg-[hsl(var(--tesla-gray)/0.3)] transition-colors">
                      <TableCell className="font-medium">
                        <div className="flex items-center gap-3">
                          <div className={`w-3 h-3 rounded-full ${
                            state.current ? 'bg-[hsl(var(--adventure-orange))] animate-pulse' : 'bg-[hsl(var(--adventure-green))]'
                          }`} />
                          <span className="font-bold text-primary">{state.state.substring(0, 2).toUpperCase()}</span>
                          <span className="text-muted-foreground">-</span>
                          <span className="font-medium">{state.state}</span>
                        </div>
                      </TableCell>
                      <TableCell>
                        {state.current ? (
                          <Badge className="bg-[hsl(var(--adventure-orange))] text-white state-badge animate-pulse">
                            🏃‍♂️ Exploring Now
                          </Badge>
                        ) : (
                          <Badge className="bg-[hsl(var(--adventure-green)/0.2)] text-[hsl(var(--adventure-green))] state-badge">
                            ✅ Conquered
                          </Badge>
                        )}
                      </TableCell>
                      <TableCell className="text-muted-foreground">
                        <div>
                          <div className="font-medium">{new Date(state.date).toLocaleDateString()}</div>
                          <div className="text-xs text-muted-foreground">
                            {Math.ceil((Date.now() - new Date(state.date).getTime()) / (1000 * 60 * 60 * 24))} days ago
                          </div>
                        </div>
                      </TableCell>
                      <TableCell>
                        <div className="space-y-1">
                          {state.highlights.map((highlight, idx) => (
                            <div key={idx} className="text-sm bg-[hsl(var(--tesla-gray))] px-2 py-1 rounded text-foreground/80">
                              {highlight}
                            </div>
                          ))}
                        </div>
                      </TableCell>
                      <TableCell>
                        <div className="flex gap-2">
                          <Button size="sm" variant="ghost" className="h-8 px-2 hover:bg-[hsl(var(--adventure-orange)/0.1)] hover:text-[hsl(var(--adventure-orange))]">
                            <Camera className="w-4 h-4" />
                          </Button>
                          <Button size="sm" variant="ghost" className="h-8 px-2 hover:bg-[hsl(var(--adventure-gold)/0.1)] hover:text-[hsl(var(--adventure-gold))]">
                            <PenTool className="w-4 h-4" />
                          </Button>
                          {state.current && (
                            <Button size="sm" variant="ghost" className="h-8 px-2 text-[hsl(var(--adventure-orange))] hover:bg-[hsl(var(--adventure-orange)/0.1)]">
                              <Target className="w-4 h-4" />
                            </Button>
                          )}
                        </div>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="map" className="space-y-6">
          <Card className="story-card">
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-gradient">
                <Route className="w-5 h-5" />
                Adventure Route Map
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="h-96 w-full">
            <LazyTeslaMap 
              mapboxToken={mapboxToken}
              onTokenChange={handleTokenChange}
              routeLocations={routeLocations}
            />
              </div>
              {routeLocations.length > 0 && (
                <div className="mt-4 p-3 bg-[hsl(var(--adventure-green)/0.1)] rounded-lg">
                  <p className="text-sm text-[hsl(var(--adventure-green))]">
                    🗺️ Route data loaded: {routeLocations.length.toLocaleString()} location points
                  </p>
                </div>
              )}
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="timeline" className="space-y-6">
          <JourneyTimeline />
        </TabsContent>

        <TabsContent value="achievements" className="space-y-6">
          <AdventureMilestones />
        </TabsContent>

        <TabsContent value="import" className="space-y-6">
          {/* Admin Mode Toggle */}
          <Card className="story-card border-[hsl(var(--adventure-orange)/0.3)]">
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-gradient">
                <PenTool className="w-5 h-5" />
                Admin Mode Access
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex items-center gap-4">
                <Button
                  variant={isAdminMode ? "default" : "outline"}
                  onClick={() => setIsAdminMode(!isAdminMode)}
                  className="gap-2"
                >
                  <Target className="w-4 h-4" />
                  {isAdminMode ? 'Exit Admin Mode' : 'Enter Admin Mode'}
                </Button>
                {isAdminMode && (
                  <Badge className="bg-[hsl(var(--adventure-orange))] text-white">
                    Admin Mode Active
                  </Badge>
                )}
              </div>
            </CardContent>
          </Card>

          {/* Data Import (Admin Only) */}
          {/* Data Import Hub removed for production security */}

          {/* Additional Admin Features */}
          {isAdminMode && (
            <Card className="story-card">
              <CardHeader>
                <CardTitle className="flex items-center gap-2 text-gradient">
                  <Camera className="w-5 h-5" />
                  Advanced Media Management
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-center p-8 border-2 border-dashed border-[hsl(var(--tesla-gray-light))] rounded-lg">
                  <Camera className="w-12 h-12 mx-auto mb-4 text-muted-foreground" />
                  <p className="text-lg font-semibold mb-2">Media Management</p>
                  <p className="text-sm text-muted-foreground">
                    Advanced media tagging and GPS extraction features available through secure import above.
                  </p>
                </div>
              </CardContent>
            </Card>
          )}
          
          {/* Import Results */}
          {importedData.length > 0 && (
            <Card className="story-card">
              <CardHeader>
                <CardTitle className="text-gradient">Import Results</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                  <div className="text-center">
                    <div className="text-2xl font-bold text-[hsl(var(--adventure-green))]">{importedData.length}</div>
                    <div className="text-sm text-muted-foreground">Data Points</div>
                  </div>
                  <div className="text-center">
                    <div className="text-2xl font-bold text-[hsl(var(--adventure-orange))]">
                      {new Set(importedData.filter(d => d.state).map(d => d.state)).size}
                    </div>
                    <div className="text-sm text-muted-foreground">States Detected</div>
                  </div>
                  <div className="text-center">
                    <div className="text-2xl font-bold text-[hsl(var(--tesla-cyan))]">
                      {Math.round(Math.max(...importedData.map(d => d.odometer || 0)))}
                    </div>
                    <div className="text-sm text-muted-foreground">Max Odometer</div>
                  </div>
                  <div className="text-center">
                    <div className="text-2xl font-bold text-[hsl(var(--adventure-purple))]">
                      {Math.round((Math.max(...importedData.map(d => d.odometer || 0)) - Math.min(...importedData.map(d => d.odometer || 0))))}</div>
                    <div className="text-sm text-muted-foreground">Trip Miles</div>
                  </div>
                </div>
              </CardContent>
            </Card>
          )}
        </TabsContent>
      </Tabs>
    </div>
  );
};

export default RoadTripTracker;