# 1Password Environment Template
# This file is used by the 1Password load-secrets-action to load secrets
# Syntax: VARIABLE_NAME=op://vault/item/field

# Core API Secrets
TESSIE_API_TOKEN=op://AWW_SHARED/prod/TESSIE_API_TOKEN
MAPBOX_API_TOKEN=op://AWW_SHARED/prod/MAPBOX_API_TOKEN
OPENWEATHER_API_KEY=op://AWW_SHARED/prod/OPENWEATHER_API_KEY

# Cloudflare Secrets
CLOUDFLARE_API_TOKEN=op://AWW_SHARED/prod/CLOUDFLARE_API_TOKEN
CLOUDFLARE_ACCOUNT_ID=op://AWW_SHARED/prod/CLOUDFLARE_ACCOUNT_ID

# Authentication Secrets
JWT_SECRET=op://AWW_SHARED/prod/JWT_SECRET
ADMIN_TOKEN=op://AWW_SHARED/prod/ADMIN_TOKEN

# Vehicle Data
TESLA_VIN=op://AWW_SHARED/prod/TESLA_VIN

# Optional Services
NOTIFICATION_WEBHOOK=op://AWW_SHARED/prod/NOTIFICATION_WEBHOOK
SPOTIFY_CLIENT_ID=op://AWW_SHARED/prod/SPOTIFY_CLIENT_ID
SPOTIFY_CLIENT_SECRET=op://AWW_SHARED/prod/SPOTIFY_CLIENT_SECRET
TAVILY_API_KEY=op://AWW_SHARED/prod/TAVILY_API_KEY
SERPER_API_KEY=op://AWW_SHARED/prod/SERPER_API_KEY
BRAVE_API_KEY=op://AWW_SHARED/prod/BRAVE_API_KEY
