import React, { useState } from "react";
import {
  Plus,
  MapPin,
  Calendar,
  Camera,
  Edit3,
  Trash2,
  Brain,
  Zap,
  TrendingUp,
  Battery,
  MessageSquare,
  Clock,
} from "lucide-react";

export default function JourneyJournal({
  entries = [],
  onAddEntry,
  currentLocation,
  isAutoGenerating,
  onGenerateEntry,
}) {
  const [isAddingEntry, setIsAddingEntry] = useState(false);
  const [newEntry, setNewEntry] = useState({
    title: "",
    content: "",
    location: "",
    photos: [],
  });

  const handleSubmit = (e) => {
    e.preventDefault();
    if (!newEntry.title.trim() || !newEntry.content.trim()) return;

    const entry = {
      id: Date.now(),
      ...newEntry,
      timestamp: new Date().toISOString(),
      type: "manual",
      autoGenerated: false,
      location:
        newEntry.location ||
        (currentLocation
          ? `${currentLocation.latitude.toFixed(4)}, ${currentLocation.longitude.toFixed(4)}`
          : "Unknown Location"),
    };

    onAddEntry(entry);
    setNewEntry({ title: "", content: "", location: "", photos: [] });
    setIsAddingEntry(false);
  };

  const formatDate = (timestamp) => {
    return new Date(timestamp).toLocaleDateString("en-US", {
      month: "short",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });
  };

  const getEntryIcon = (entry) => {
    if (entry.autoGenerated) {
      switch (entry.type) {
        case "charging_started":
        case "charging_completed":
          return <Zap className="h-4 w-4 text-green-600" />;
        case "location_change":
          return <MapPin className="h-4 w-4 text-blue-600" />;
        case "efficiency_milestone":
          return <TrendingUp className="h-4 w-4 text-purple-600" />;
        case "low_battery_warning":
          return <Battery className="h-4 w-4 text-red-600" />;
        default:
          return <Brain className="h-4 w-4 text-purple-600" />;
      }
    }
    return <MessageSquare className="h-4 w-4 text-gray-600" />;
  };

  return (
    <div className="h-96 flex flex-col">
      {/* Enhanced Header with AI Status */}
      <div className="p-4 border-b">
        <div className="flex items-center justify-between mb-3">
          {isAutoGenerating && (
            <div className="flex items-center space-x-2 text-sm text-purple-600">
              <Brain className="h-4 w-4 animate-pulse" />
              <span>AI writing entry...</span>
            </div>
          )}
          <button
            onClick={() => setIsAddingEntry(true)}
            className="ml-auto flex items-center justify-center space-x-2 px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors"
          >
            <Plus className="h-4 w-4" />
            <span>Add Journal Entry</span>
          </button>
        </div>

        {/* AI Generation Buttons */}
        {onGenerateEntry && (
          <div className="flex items-center space-x-2 mb-3">
            <span className="text-xs text-gray-500">AI Generate:</span>
            <button
              onClick={() => onGenerateEntry("location_change")}
              className="px-2 py-1 text-xs bg-blue-100 text-blue-600 rounded hover:bg-blue-200 transition-colors"
              disabled={isAutoGenerating}
            >
              <MapPin className="h-3 w-3 inline mr-1" />
              Location Update
            </button>
            <button
              onClick={() => onGenerateEntry("efficiency_milestone")}
              className="px-2 py-1 text-xs bg-green-100 text-green-600 rounded hover:bg-green-200 transition-colors"
              disabled={isAutoGenerating}
            >
              <TrendingUp className="h-3 w-3 inline mr-1" />
              Efficiency Check
            </button>
          </div>
        )}
      </div>

      {/* Add Entry Form */}
      {isAddingEntry && (
        <div className="p-4 border-b bg-gray-50">
          <form onSubmit={handleSubmit} className="space-y-3">
            <input
              type="text"
              placeholder="Entry title..."
              value={newEntry.title}
              onChange={(e) =>
                setNewEntry((prev) => ({ ...prev, title: e.target.value }))
              }
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-transparent"
              autoFocus
            />
            <textarea
              placeholder="What happened on your journey?"
              value={newEntry.content}
              onChange={(e) =>
                setNewEntry((prev) => ({ ...prev, content: e.target.value }))
              }
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-transparent resize-none"
              rows={3}
            />
            <input
              type="text"
              placeholder="Location (optional)"
              value={newEntry.location}
              onChange={(e) =>
                setNewEntry((prev) => ({ ...prev, location: e.target.value }))
              }
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-transparent"
            />
            <div className="flex space-x-2">
              <button
                type="submit"
                className="flex-1 px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors"
              >
                Save Entry
              </button>
              <button
                type="button"
                onClick={() => {
                  setIsAddingEntry(false);
                  setNewEntry({
                    title: "",
                    content: "",
                    location: "",
                    photos: [],
                  });
                }}
                className="px-4 py-2 bg-gray-300 text-gray-700 rounded-lg hover:bg-gray-400 transition-colors"
              >
                Cancel
              </button>
            </div>
          </form>
        </div>
      )}

      {/* Entries List */}
      <div className="flex-1 overflow-y-auto">
        {entries.length === 0 ? (
          <div className="p-8 text-center text-gray-500">
            <div className="flex justify-center space-x-2 mb-4">
              <Edit3 className="h-8 w-8 text-gray-300" />
              <Brain className="h-8 w-8 text-purple-300" />
            </div>
            <p className="text-sm">No journal entries yet.</p>
            <p className="text-xs text-gray-400 mt-1">
              AI will automatically create entries as you drive, or add your
              own!
            </p>
          </div>
        ) : (
          <div className="p-4 space-y-4">
            {entries.map((entry) => (
              <div
                key={entry.id}
                className={`border rounded-lg p-4 shadow-sm transition-all hover:shadow-md ${
                  entry.autoGenerated
                    ? "bg-gradient-to-r from-purple-50 to-blue-50 border-purple-200"
                    : "bg-white border-gray-200"
                }`}
              >
                <div className="flex items-start justify-between mb-2">
                  <div className="flex items-center space-x-2 flex-1">
                    {getEntryIcon(entry)}
                    <h4 className="font-semibold text-gray-900 text-sm">
                      {entry.title}
                    </h4>
                    {entry.autoGenerated && (
                      <span className="flex items-center space-x-1 px-1.5 py-0.5 bg-purple-100 text-purple-600 text-xs rounded-full">
                        <Brain className="h-2.5 w-2.5" />
                        <span>AI</span>
                      </span>
                    )}
                  </div>
                  <div className="flex items-center space-x-1">
                    <button className="p-1 text-gray-400 hover:text-gray-600">
                      <Edit3 className="h-3 w-3" />
                    </button>
                    <button className="p-1 text-gray-400 hover:text-red-600">
                      <Trash2 className="h-3 w-3" />
                    </button>
                  </div>
                </div>

                <p className="text-sm text-gray-700 mb-3 leading-relaxed">
                  {entry.content}
                </p>

                <div className="flex items-center justify-between text-xs text-gray-500">
                  <div className="flex items-center space-x-4">
                    <div className="flex items-center space-x-1">
                      <Calendar className="h-3 w-3" />
                      <span>{formatDate(entry.timestamp)}</span>
                    </div>
                    {entry.location && (
                      <div className="flex items-center space-x-1">
                        <MapPin className="h-3 w-3" />
                        <span className="truncate max-w-24">
                          {typeof entry.location === "string"
                            ? entry.location
                            : entry.location.name}
                        </span>
                      </div>
                    )}
                    {entry.vehicleStats && (
                      <div className="flex items-center space-x-1">
                        <Battery className="h-3 w-3" />
                        <span>{entry.vehicleStats.battery}%</span>
                      </div>
                    )}
                  </div>
                  <div className="flex items-center space-x-2">
                    {entry.photos && entry.photos.length > 0 && (
                      <div className="flex items-center space-x-1">
                        <Camera className="h-3 w-3" />
                        <span>{entry.photos.length}</span>
                      </div>
                    )}
                    {entry.mood && (
                      <span className="text-xs">
                        {entry.mood === "excited" && "🚗"}
                        {entry.mood === "happy" && "😊"}
                        {entry.mood === "satisfied" && "👍"}
                        {entry.mood === "neutral" && "📝"}
                        {entry.mood === "concerned" && "😐"}
                        {entry.mood === "frustrated" && "😤"}
                      </span>
                    )}
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Enhanced Quick Entry Templates */}
      <div className="p-4 border-t bg-gray-50">
        <p className="text-xs text-gray-600 mb-2">Quick entries:</p>
        <div className="flex flex-wrap gap-1">
          {[
            "Charging stop",
            "Scenic view",
            "Food break",
            "Rest stop",
            "Milestone reached",
            "Great efficiency!",
          ].map((template) => (
            <button
              key={template}
              onClick={() => {
                setNewEntry((prev) => ({
                  ...prev,
                  title: template,
                  content: `${template} at ${
                    currentLocation
                      ? `${currentLocation.latitude.toFixed(4)}, ${currentLocation.longitude.toFixed(4)}`
                      : "current location"
                  }`,
                }));
                setIsAddingEntry(true);
              }}
              className="px-2 py-1 text-xs bg-white border border-gray-200 rounded text-gray-600 hover:bg-gray-100 transition-colors"
            >
              {template}
            </button>
          ))}
        </div>
      </div>
    </div>
  );
}
