import { detectStateFromCoordinates } from '@/utils/stateDetection';
import { journeyTimeline, type TimelineEvent } from '@/data/journeyData';
import { WeatherData } from './weatherService';

interface DriveSession {
  startTime: number;
  endTime: number;
  startLocation: { lat: number; lng: number };
  endLocation: { lat: number; lng: number };
  distance: number;
  averageSpeed: number;
  maxSpeed: number;
}

interface ChargeSession {
  startTime: number;
  endTime?: number;
  location: { lat: number; lng: number };
  startBattery: number;
  endBattery?: number;
  energyAdded: number;
  chargerType: string;
  chargerPower?: number;
}

interface OvernightStop {
  startTime: number;
  endTime?: number;
  location: { lat: number; lng: number };
  type: 'hotel' | 'camping' | 'rest_area' | 'unknown';
  duration: number;
}

interface EnhancedTimelineEvent extends TimelineEvent {
  id: string;
  endDate?: string;
  weather?: WeatherData;
  driveData?: DriveSession;
  chargeData?: ChargeSession;
  overnightData?: OvernightStop;
  autoGenerated: boolean;
  lastUpdated: number;
}

class TimelineService {
  private static readonly STORAGE_KEY = 'journey_timeline_enhanced';
  private static readonly OVERNIGHT_THRESHOLD = 6 * 60 * 60 * 1000; // 6 hours
  private static readonly STATIONARY_THRESHOLD = 0.001; // degrees (~100m)
  
  private enhancedTimeline: EnhancedTimelineEvent[] = [];
  private lastKnownLocation: { lat: number; lng: number } | null = null;
  private lastKnownState: string | null = null;
  private currentChargeSession: ChargeSession | null = null;
  private currentOvernightStop: OvernightStop | null = null;
  private stationaryStartTime: number | null = null;

  constructor() {
    this.loadFromStorage();
    this.initializeFromStaticData();
  }

  private loadFromStorage(): void {
    try {
      const stored = localStorage.getItem(TimelineService.STORAGE_KEY);
      if (stored) {
        this.enhancedTimeline = JSON.parse(stored);
      }
    } catch (error) {
      console.warn('Failed to load timeline from storage:', error);
    }
  }

  private saveToStorage(): void {
    try {
      localStorage.setItem(TimelineService.STORAGE_KEY, JSON.stringify(this.enhancedTimeline));
    } catch (error) {
      console.warn('Failed to save timeline to storage:', error);
    }
  }

  private initializeFromStaticData(): void {
    // Always ensure we have the static timeline data
    const hasStaticData = this.enhancedTimeline.some(event => !event.autoGenerated);
    
    if (!hasStaticData) {
      console.log('Initializing timeline with static journey data');
      const staticEvents = journeyTimeline.map((event, index) => ({
        ...event,
        id: `static_${index}`,
        autoGenerated: false,
        lastUpdated: Date.now()
      }));
      
      this.enhancedTimeline = [...staticEvents, ...this.enhancedTimeline.filter(e => e.autoGenerated)];
      this.saveToStorage();
      console.log('Timeline initialized with', this.enhancedTimeline.length, 'events');
    }
  }

  private generateEventId(): string {
    return `auto_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
  }

  private isLocationStationary(lat: number, lng: number): boolean {
    if (!this.lastKnownLocation) return false;
    
    const latDiff = Math.abs(lat - this.lastKnownLocation.lat);
    const lngDiff = Math.abs(lng - this.lastKnownLocation.lng);
    
    return latDiff < TimelineService.STATIONARY_THRESHOLD && 
           lngDiff < TimelineService.STATIONARY_THRESHOLD;
  }

  private isNighttime(): boolean {
    const hour = new Date().getHours();
    return hour >= 20 || hour <= 8; // 8PM to 8AM
  }

  updateVehicleData(vehicleData: any): void {
    try {
      console.log('TimelineService: Received vehicle data:', vehicleData);
      
      // Handle both flat and nested vehicle data structures
      let drive_state, charge_state;
      
      if (vehicleData?.last_state?.drive_state) {
        // Full Tessie API structure
        drive_state = vehicleData.last_state.drive_state;
        charge_state = vehicleData.last_state.charge_state;
      } else if (vehicleData?.latitude && vehicleData?.longitude) {
        // Flattened structure - create compatible format
        drive_state = {
          latitude: vehicleData.latitude,
          longitude: vehicleData.longitude,
          speed: vehicleData.speed,
          heading: vehicleData.heading,
          timestamp: vehicleData.timestamp
        };
        charge_state = {
          charging_state: vehicleData.charging_state,
          battery_level: vehicleData.battery_level,
          charge_energy_added: 0,
          fast_charger_brand: null,
          charger_power: 0
        };
      } else {
        console.warn('TimelineService: Invalid vehicle data structure');
        return;
      }
      const currentLat = drive_state.latitude;
      const currentLng = drive_state.longitude;
      const currentTime = Date.now();
      const isCharging = charge_state?.charging_state === 'Charging';
      const batteryLevel = charge_state?.battery_level || 0;

      if (!currentLat || !currentLng) {
        console.warn('TimelineService: No valid location data in vehicle state');
        return;
      }

      console.log('TimelineService: Processing location:', { 
        lat: currentLat, 
        lng: currentLng, 
        isCharging, 
        batteryLevel,
        speed: drive_state.speed 
      });

      // Check for state boundary crossing with REAL GPS data
      this.checkStateBoundaryCrossing(currentLat, currentLng, currentTime);

      // Handle charging sessions with REAL charge data
      if (charge_state) {
        this.handleChargingSession(currentLat, currentLng, currentTime, isCharging, batteryLevel, charge_state);
      }

      // Handle overnight stops with REAL movement data
      this.handleOvernightStops(currentLat, currentLng, currentTime);

      // Update location tracking with REAL coordinates
      this.lastKnownLocation = { lat: currentLat, lng: currentLng };
      
      console.log('TimelineService: Location tracking updated to:', this.lastKnownLocation);
    } catch (error) {
      console.error('TimelineService: Error updating with vehicle data:', error);
    }
  }

  private checkStateBoundaryCrossing(lat: number, lng: number, timestamp: number): void {
    const currentState = detectStateFromCoordinates(lat, lng);
    
    console.log('TimelineService: State detection result:', { 
      coordinates: { lat, lng }, 
      detectedState: currentState?.name,
      lastKnownState: this.lastKnownState 
    });
    
    if (currentState && currentState.name !== this.lastKnownState) {
      console.log(`🎉 TimelineService: State boundary crossing detected! ${this.lastKnownState} → ${currentState.name}`);
      
      // Check if we already have an event for this state
      const existingEvent = this.enhancedTimeline.find(event => 
        event.state === currentState.name && event.autoGenerated
      );

      if (!existingEvent) {
        console.log(`TimelineService: Creating new auto-generated event for ${currentState.name}`);
        
        // Create new state event with REAL data
        const newEvent: EnhancedTimelineEvent = {
          id: this.generateEventId(),
          state: currentState.name,
          date: new Date(timestamp).toLocaleDateString(),
          highlights: [
            `🚗 Entered ${currentState.name} at ${new Date(timestamp).toLocaleTimeString()}`,
            `📍 GPS: ${lat.toFixed(4)}, ${lng.toFixed(4)}`,
            `🤖 Auto-detected from live vehicle data`
          ],
          type: 'milestone',
          current: true,
          location: { lat, lng },
          autoGenerated: true,
          lastUpdated: timestamp
        };

        // Mark previous current state as not current
        this.enhancedTimeline.forEach(event => {
          if (event.current) {
            event.current = false;
            console.log(`TimelineService: Marked ${event.state} as no longer current`);
          }
        });

        this.enhancedTimeline.push(newEvent);
        this.saveToStorage();
        
        console.log(`🎉 TimelineService: New state event created for ${currentState.name}`);
      } else if (!existingEvent.current) {
        // Mark as current if returning to a previously visited state
        console.log(`TimelineService: Marking ${currentState.name} as current (returning to previous state)`);
        this.enhancedTimeline.forEach(event => {
          event.current = event.id === existingEvent.id;
        });
        
        // Update the existing event with current location
        existingEvent.location = { lat, lng };
        existingEvent.lastUpdated = timestamp;
        existingEvent.highlights = [
          ...existingEvent.highlights.filter(h => !h.includes('Returned to')),
          `🔄 Returned to ${currentState.name} at ${new Date(timestamp).toLocaleTimeString()}`,
          `📍 Current GPS: ${lat.toFixed(4)}, ${lng.toFixed(4)}`
        ];
        
        this.saveToStorage();
      }

      this.lastKnownState = currentState.name;
      console.log(`TimelineService: lastKnownState updated to: ${this.lastKnownState}`);
    } else if (!currentState) {
      console.warn('TimelineService: Could not detect state from coordinates:', { lat, lng });
    }
  }

  private handleChargingSession(
    lat: number, 
    lng: number, 
    timestamp: number, 
    isCharging: boolean, 
    batteryLevel: number,
    chargeState: any
  ): void {
    if (isCharging && !this.currentChargeSession) {
      // Start new charging session
      this.currentChargeSession = {
        startTime: timestamp,
        location: { lat, lng },
        startBattery: batteryLevel,
        energyAdded: chargeState.charge_energy_added || 0,
        chargerType: chargeState.fast_charger_brand || 'Standard',
        chargerPower: chargeState.charger_power || 0
      };
    } else if (!isCharging && this.currentChargeSession) {
      // End charging session
      this.currentChargeSession.endTime = timestamp;
      this.currentChargeSession.endBattery = batteryLevel;
      
      const duration = Math.round((timestamp - this.currentChargeSession.startTime) / (1000 * 60)); // minutes
      const energyGained = batteryLevel - this.currentChargeSession.startBattery;
      
      // Create charging event
      const chargingEvent: EnhancedTimelineEvent = {
        id: this.generateEventId(),
        state: this.lastKnownState || 'Unknown',
        date: new Date(timestamp).toLocaleDateString(),
        highlights: [
          `Charging session: ${duration} minutes`,
          `Battery: ${this.currentChargeSession.startBattery}% → ${batteryLevel}% (+${energyGained}%)`
        ],
        type: 'adventure',
        location: this.currentChargeSession.location,
        chargeData: this.currentChargeSession,
        autoGenerated: true,
        lastUpdated: timestamp
      };

      this.enhancedTimeline.push(chargingEvent);
      this.saveToStorage();
      
      console.log(`🔋 Charging session completed: +${energyGained}% in ${duration} minutes`);
      this.currentChargeSession = null;
    }
  }

  private handleOvernightStops(lat: number, lng: number, timestamp: number): void {
    const isStationary = this.isLocationStationary(lat, lng);
    
    if (isStationary) {
      if (!this.stationaryStartTime) {
        this.stationaryStartTime = timestamp;
      }
      
      // Check if we've been stationary long enough and it's nighttime
      const stationaryDuration = timestamp - this.stationaryStartTime;
      if (stationaryDuration >= TimelineService.OVERNIGHT_THRESHOLD && 
          this.isNighttime() && 
          !this.currentOvernightStop) {
        
        this.currentOvernightStop = {
          startTime: this.stationaryStartTime,
          location: { lat, lng },
          type: 'unknown', // Could be enhanced with location services
          duration: 0
        };
      }
    } else {
      // Vehicle started moving
      if (this.currentOvernightStop) {
        this.currentOvernightStop.endTime = timestamp;
        this.currentOvernightStop.duration = timestamp - this.currentOvernightStop.startTime;
        
        const hours = Math.round(this.currentOvernightStop.duration / (1000 * 60 * 60));
        
        // Create overnight stop event
        const overnightEvent: EnhancedTimelineEvent = {
          id: this.generateEventId(),
          state: this.lastKnownState || 'Unknown',
          date: new Date(this.currentOvernightStop.startTime).toLocaleDateString(),
          endDate: new Date(timestamp).toLocaleDateString(),
          highlights: [
            `Overnight stop: ${hours} hours`,
            `Rest period from ${new Date(this.currentOvernightStop.startTime).toLocaleTimeString()} to ${new Date(timestamp).toLocaleTimeString()}`
          ],
          type: 'cultural',
          location: this.currentOvernightStop.location,
          overnightData: this.currentOvernightStop,
          autoGenerated: true,
          lastUpdated: timestamp
        };

        this.enhancedTimeline.push(overnightEvent);
        this.saveToStorage();
        
        console.log(`🌙 Overnight stop completed: ${hours} hours`);
        this.currentOvernightStop = null;
      }
      
      this.stationaryStartTime = null;
    }
  }

  addWeatherToEvent(eventId: string, weather: WeatherData): void {
    const event = this.enhancedTimeline.find(e => e.id === eventId);
    if (event) {
      event.weather = weather;
      event.lastUpdated = Date.now();
      this.saveToStorage();
    }
  }

  getTimeline(): EnhancedTimelineEvent[] {
    // Sort by date, with current events first
    return [...this.enhancedTimeline].sort((a, b) => {
      if (a.current && !b.current) return -1;
      if (!a.current && b.current) return 1;
      return new Date(b.date).getTime() - new Date(a.date).getTime();
    });
  }

  getCurrentEvent(): EnhancedTimelineEvent | null {
    return this.enhancedTimeline.find(event => event.current) || null;
  }

  getRecentEvents(limit: number = 5): EnhancedTimelineEvent[] {
    return this.getTimeline()
      .filter(event => event.autoGenerated)
      .slice(0, limit);
  }

  exportTimeline(): string {
    return JSON.stringify(this.enhancedTimeline, null, 2);
  }

  importTimeline(data: string): boolean {
    try {
      const imported = JSON.parse(data);
      if (Array.isArray(imported)) {
        this.enhancedTimeline = imported;
        this.saveToStorage();
        return true;
      }
    } catch (error) {
      console.error('Failed to import timeline:', error);
    }
    return false;
  }

  clearAutoGeneratedEvents(): void {
    this.enhancedTimeline = this.enhancedTimeline.filter(event => !event.autoGenerated);
    this.saveToStorage();
  }
}

export { TimelineService, type EnhancedTimelineEvent, type DriveSession, type ChargeSession, type OvernightStop };