// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wlnmnzhzzgslphhpsafk.supabase.co";
// Supabase publishable key must be supplied via environment variables.
// Do NOT commit real keys. Replace at build time with Vite's VITE_SUPABASE_PUBLISHABLE_KEY.
const SUPABASE_PUBLISHABLE_KEY = typeof import.meta !== 'undefined' && import.meta.env && import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY
  ? String(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY)
  : '';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});