// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wlnmnzhzzgslphhpsafk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indsbm1uemh6emdzbHBoaHBzYWZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MTgyODQsImV4cCI6MjA2NTI5NDI4NH0.NvarlqeSBloP6RmsuPxWpn4xVHTlUsNTFYOs9gF31MY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});