import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { MapPin, Calendar, Camera, Star, Mountain, Sunset, Cloud, Zap, Navigation } from 'lucide-react';

interface TimelineEvent {
  id: string;
  state: string;
  date: string;
  type: 'milestone' | 'scenic' | 'adventure' | 'cultural';
  highlights: string[];
  location?: { lat: number; lng: number };
  weather?: { temperature: number; condition: string };
  current?: boolean;
  autoGenerated?: boolean;
}

interface JourneyTimelineProps {
  events?: TimelineEvent[];
  isLoading?: boolean;
  currentLocation?: { lat: number; lng: number } | null;
  batteryLevel?: number;
  isCharging?: boolean;
}

const getTypeIcon = (type: string) => {
  switch (type) {
    case 'milestone': return Star;
    case 'scenic': return Mountain;
    case 'adventure': return Camera;
    case 'cultural': return Sunset;
    default: return MapPin;
  }
};

const getTypeColor = (type: string) => {
  switch (type) {
    case 'milestone': return 'text-adventure-gold';
    case 'scenic': return 'text-adventure-green';
    case 'adventure': return 'text-adventure-orange';
    case 'cultural': return 'text-adventure-purple';
    default: return 'text-primary';
  }
};

// Sample timeline events based on actual journey
const defaultEvents: TimelineEvent[] = [
  {
    id: '1',
    state: 'Texas',
    date: '2025-06-03',
    type: 'milestone',
    highlights: ['Journey begins in Corpus Christi', 'Final prep and vehicle check', 'First charging session'],
    location: { lat: 27.8006, lng: -97.3964 },
    weather: { temperature: 89, condition: 'Sunny' }
  },
  {
    id: '2',
    state: 'New Mexico',
    date: '2025-06-08',
    type: 'scenic',
    highlights: ['Crossed into New Mexico', 'White Sands National Park', 'Desert sunset photography'],
    location: { lat: 32.7872, lng: -105.9378 },
    weather: { temperature: 95, condition: 'Clear' }
  },
  {
    id: '3',
    state: 'Arizona',
    date: '2025-06-12',
    type: 'adventure',
    highlights: ['Grand Canyon visit', 'Supercharger stop in Flagstaff', 'Incredible canyon views'],
    location: { lat: 36.0544, lng: -112.1401 },
    weather: { temperature: 78, condition: 'Partly Cloudy' }
  },
  {
    id: '4',
    state: 'California',
    date: '2025-06-15',
    type: 'milestone',
    highlights: ['Pacific Coast Highway', 'First ocean view of the trip', 'Charged at Monterey SC'],
    location: { lat: 36.6002, lng: -121.8947 },
    weather: { temperature: 68, condition: 'Foggy' }
  },
  {
    id: '5',
    state: 'Oregon',
    date: '2025-06-20',
    type: 'scenic',
    highlights: ['Crater Lake National Park', 'Stunning blue water', 'Perfect weather for photos'],
    location: { lat: 42.9446, lng: -122.1090 },
    weather: { temperature: 72, condition: 'Sunny' }
  },
];

const JourneyTimeline: React.FC<JourneyTimelineProps> = ({
  events = defaultEvents,
  isLoading = false,
  currentLocation = null,
  batteryLevel,
  isCharging = false
}) => {
  if (isLoading && events.length === 0) {
    return (
      <Card className="card-tesla">
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-gradient-primary">
            <Calendar className="w-5 h-5" />
            Journey Chronicles
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="flex items-center justify-center p-8">
            <div className="text-center">
              <div className="w-8 h-8 border-2 border-primary border-t-transparent rounded-full animate-spin mx-auto mb-4"></div>
              <p className="text-muted-foreground">Loading journey timeline...</p>
            </div>
          </div>
        </CardContent>
      </Card>
    );
  }

  if (events.length === 0) {
    return (
      <Card className="card-tesla">
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-gradient-primary">
            <Calendar className="w-5 h-5" />
            Journey Chronicles
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="flex items-center justify-center p-8">
            <div className="text-center">
              <Calendar className="w-12 h-12 mx-auto mb-4 text-muted-foreground" />
              <p className="text-lg font-semibold mb-2">No Timeline Data</p>
              <p className="text-sm text-muted-foreground">
                Timeline will populate when journey data is imported.
              </p>
            </div>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card className="card-tesla">
      <CardHeader>
        <CardTitle className="flex items-center gap-2 text-gradient-primary flex-wrap">
          <Calendar className="w-5 h-5" />
          Journey Chronicles
          <Badge className="ml-auto bg-tesla-blue/20 text-tesla-blue border-0">
            {events.length} Events
          </Badge>
          {currentLocation && (
            <Badge className="bg-adventure-orange/20 text-adventure-orange border-0">
              <Navigation className="w-3 h-3 mr-1" />
              Live GPS
            </Badge>
          )}
          {batteryLevel !== undefined && (
            <Badge className={`${isCharging ? 'bg-adventure-green/20 text-adventure-green' : 'bg-tesla-blue/20 text-tesla-blue'} border-0`}>
              <Zap className="w-3 h-3 mr-1" />
              {batteryLevel}% {isCharging ? '⚡' : '🔋'}
            </Badge>
          )}
        </CardTitle>
      </CardHeader>
      <CardContent>
        {/* Live Vehicle Status */}
        {currentLocation && (
          <div className="mb-6 p-4 bg-adventure-orange/10 rounded-lg border border-adventure-orange/20">
            <h4 className="font-semibold text-adventure-orange mb-2 flex items-center gap-2">
              <Navigation className="w-4 h-4" />
              Live Vehicle Status
            </h4>
            <div className="grid grid-cols-2 gap-4 text-sm">
              <div>
                <span className="text-muted-foreground">Location: </span>
                <span className="font-mono text-foreground">{currentLocation.lat.toFixed(4)}, {currentLocation.lng.toFixed(4)}</span>
              </div>
              {batteryLevel !== undefined && (
                <div>
                  <span className="text-muted-foreground">Battery: </span>
                  <span className={batteryLevel < 30 ? 'text-destructive' : 'text-foreground'}>
                    {batteryLevel}% {isCharging ? '(Charging)' : ''}
                  </span>
                </div>
              )}
            </div>
          </div>
        )}

        <div className="relative">
          {/* Timeline line */}
          <div className="absolute left-6 top-4 bottom-4 w-0.5 bg-gradient-to-b from-tesla-blue via-adventure-orange to-muted" />

          <div className="space-y-6">
            {events.map((event, index) => {
              const IconComponent = getTypeIcon(event.type);
              const iconColor = getTypeColor(event.type);
              const isCurrent = event.current;

              return (
                <div key={event.id || index} className="relative flex gap-4">
                  {/* Timeline dot */}
                  <div className={`relative z-10 flex items-center justify-center w-12 h-12 rounded-full ${
                    isCurrent ? 'bg-adventure-orange pulse-glow' :
                    'bg-secondary'
                  } border-2 border-background`}>
                    <IconComponent className={`w-5 h-5 ${
                      isCurrent ? 'text-primary-foreground' : iconColor
                    }`} />
                  </div>

                  {/* Event content */}
                  <div className="flex-1 pb-6">
                    <div className="flex items-center gap-3 mb-2 flex-wrap">
                      <h3 className="font-bold text-lg text-foreground">{event.state}</h3>
                      {isCurrent && (
                        <Badge className="bg-adventure-orange text-primary-foreground text-xs border-0">
                          Current Location
                        </Badge>
                      )}
                      <Badge className="bg-tesla-blue/20 text-tesla-blue text-xs border-0">
                        {event.type.charAt(0).toUpperCase() + event.type.slice(1)}
                      </Badge>
                    </div>

                    <div className="flex items-center gap-4 mb-3 flex-wrap">
                      <p className="text-sm text-muted-foreground">{new Date(event.date).toLocaleDateString()}</p>
                      {event.weather && (
                        <div className="flex items-center gap-2 text-xs">
                          <Cloud className="w-3 h-3 text-tesla-blue" />
                          <span className="text-tesla-blue">
                            {Math.round(event.weather.temperature)}°F
                          </span>
                        </div>
                      )}
                      {event.location && (
                        <div className="flex items-center gap-2 text-xs">
                          <MapPin className="w-3 h-3 text-muted-foreground" />
                          <span className="text-muted-foreground font-mono">
                            {event.location.lat.toFixed(3)}, {event.location.lng.toFixed(3)}
                          </span>
                        </div>
                      )}
                    </div>

                    <div className="space-y-2">
                      {event.highlights.map((highlight, idx) => (
                        <div key={idx} className="flex items-start gap-2">
                          <div className="w-1.5 h-1.5 bg-adventure-gold rounded-full mt-2 flex-shrink-0" />
                          <span className="text-sm text-foreground/80">
                            {highlight}
                          </span>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </CardContent>
    </Card>
  );
};

export default JourneyTimeline;
