#!/bin/bash
# Full site verification script
# This script combines multiple tests to verify that all components are working correctly

echo "====================================================="
echo "🔍 48 Continental USA Complete Verification Suite"
echo "====================================================="
echo "Running tests on $(date)"

# Directory for this script
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd "$SCRIPT_DIR"

# Environment configuration
PUBLIC_SITE_URL="https://main.continentalusa-site.pages.dev"
EDGE_WORKER_URL="https://thewanderingwhittle-edge.kd8jc7v8cd.workers.dev"
TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
REPORT_FILE="./verification_reports/complete_verification_${TIMESTAMP}.md"

# Create directory for reports if it doesn't exist
mkdir -p ./verification_reports

# 1. Check environment variables
echo -e "\n1. Checking environment configuration..."
./check-env.sh

# 2. Verify site availability
echo -e "\n2. Verifying site availability..."
PUBLIC_SITE_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$PUBLIC_SITE_URL")
EDGE_WORKER_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$EDGE_WORKER_URL")

if [ "$PUBLIC_SITE_STATUS" -eq 200 ]; then
  echo "✅ Public site is accessible ($PUBLIC_SITE_STATUS)"
else
  echo "❌ Public site returned status $PUBLIC_SITE_STATUS"
fi

if [ "$EDGE_WORKER_STATUS" -eq 200 ]; then
  echo "✅ Edge Worker is accessible ($EDGE_WORKER_STATUS)"
else
  echo "❌ Edge Worker returned status $EDGE_WORKER_STATUS"
fi

# 3. Check basic API endpoints
echo -e "\n3. Testing API endpoints..."
API_ENDPOINTS=(
  "$EDGE_WORKER_URL/api/itinerary"
  "$EDGE_WORKER_URL/api/v1/status"
  "$EDGE_WORKER_URL/api/weather"
)

for endpoint in "${API_ENDPOINTS[@]}"; do
  STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$endpoint")
  if [ "$STATUS" -eq 200 ] || [ "$STATUS" -eq 204 ]; then
    echo "✅ $endpoint - Status: $STATUS"
  else
    echo "❌ $endpoint - Status: $STATUS"
  fi
done

# 4. Check for key resources on public site
echo -e "\n4. Verifying resource availability..."
# We need to follow redirects for index.html and assets
echo "Checking index.html availability..."
INDEX_STATUS=$(curl -L -s -o /dev/null -w "%{http_code}" "$PUBLIC_SITE_URL/")
if [ "$INDEX_STATUS" -eq 200 ]; then
  echo "✅ $PUBLIC_SITE_URL/ is accessible"
else
  echo "❌ $PUBLIC_SITE_URL/ returned status $INDEX_STATUS"
fi

echo "Checking assets availability..."
# For assets, we'll get the main JS file URL from the HTML and check it
ASSETS_HTML=$(curl -L -s "$PUBLIC_SITE_URL")
if [[ $ASSETS_HTML == *"assets/index-"* ]]; then
  echo "✅ Assets references found in HTML"
else
  echo "❌ No references to assets found in HTML"
fi

# 5. Generate report
echo -e "\n5. Generating verification report..."
cat > "$REPORT_FILE" << EOL
# 48 Continental USA Verification Report

**Date:** $(date)
**Report Generated By:** complete-verify.sh

## Component Status

| Component | Status | Details |
|-----------|--------|---------|
| Public Site | $([ "$PUBLIC_SITE_STATUS" -eq 200 ] && echo "✅ Working" || echo "❌ Not Working") | HTTP $PUBLIC_SITE_STATUS |
| Edge Worker | $([ "$EDGE_WORKER_STATUS" -eq 200 ] && echo "✅ Working" || echo "❌ Not Working") | HTTP $EDGE_WORKER_STATUS |

## API Endpoint Status

$(
  for endpoint in "${API_ENDPOINTS[@]}"; do
    STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$endpoint")
    if [ "$STATUS" -eq 200 ] || [ "$STATUS" -eq 204 ]; then
      echo "- $endpoint: ✅ HTTP $STATUS"
    else
      echo "- $endpoint: ❌ HTTP $STATUS"
    fi
  done
)

## Next Steps

Please complete the manual verification using:
1. Open the website: $PUBLIC_SITE_URL
2. Use the verification-checklist.md to manually verify all functionality

Reminder: The site leverages simulated data for reliability when the real API is unavailable.
EOL

echo "Complete verification report saved to: $REPORT_FILE"
echo -e "\n====================================================="
echo "Verification process complete!"
echo "To perform manual verification, open: $PUBLIC_SITE_URL"
echo "and follow the steps in verification-checklist.md"
echo "====================================================="
