#!/bin/bash

# IMMEDIATE FIX FOR REAL-TIME DATA ISSUE
# The app isn't working because development has NO API keys!

echo "🚨 CRITICAL: App not working because development has 0/5 API keys!"
echo ""
echo "🔧 IMMEDIATE FIXES NEEDED:"
echo ""
echo "📍 Navigate to backend directory:"
echo "   cd backend/edge-worker"
echo ""
echo "🔑 Set development secrets (copy values from production):"
echo "   npx wrangler secret put TESSIE_API_KEY --env development"
echo "   npx wrangler secret put MAPBOX_ACCESS_TOKEN --env development"
echo "   npx wrangler secret put JWT_SECRET --env development"
echo "   npx wrangler secret put TESLA_VIN --env development"
echo "   npx wrangler secret put ADMIN_PASSWORD --env development"
echo ""
echo "🌤️  Also add missing production secret:"
echo "   npx wrangler secret put OPENWEATHER_API_KEY --env production"
echo "   npx wrangler secret put OPENWEATHER_API_KEY --env development"
echo ""
echo "✅ Verify configuration:"
echo "   cd ../../"
echo "   npm run api:audit"
echo ""
echo "🚀 Deploy to activate:"
echo "   cd backend/edge-worker"
echo "   npx wrangler deploy --env development"
echo ""
echo "📊 Test real-time data:"
echo "   curl https://awhittlewandering-api-dev.kd8jc7v8cd.workers.dev/api/v1/tesla/telemetry"
