import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Outlet, Link, useLocation } from 'react-router-dom';
export default function Layout() {
    const location = useLocation();
    const isActive = (path) => {
        return location.pathname === path ? 'active' : '';
    };
    return (_jsxs("div", { className: "app-container", children: [_jsxs("header", { className: "app-header", children: [_jsx("div", { className: "logo", children: _jsxs(Link, { to: "/", children: [_jsx("h1", { children: "A Whittle Wandering" }), _jsx("span", { className: "tagline", children: "60 days, 48 states, One Tesla, One epic journey" })] }) }), _jsx("nav", { className: "main-nav", children: _jsxs("ul", { children: [_jsx("li", { className: isActive('/'), children: _jsx(Link, { to: "/", children: "Home" }) }), _jsx("li", { className: isActive('/map'), children: _jsx(Link, { to: "/map", children: "Live Map" }) }), _jsx("li", { className: isActive('/daily-log') || location.pathname.startsWith('/daily-log/'), children: _jsx(Link, { to: "/daily-log", children: "Daily Log" }) }), _jsx("li", { className: isActive('/about'), children: _jsx(Link, { to: "/about", children: "About" }) })] }) })] }), _jsx("main", { className: "app-content", children: _jsx(Outlet, {}) }), _jsxs("footer", { className: "app-footer", children: [_jsxs("div", { className: "footer-content", children: [_jsxs("div", { className: "footer-section", children: [_jsx("h3", { children: "A Whittle Wandering" }), _jsxs("p", { children: ["\u00A9 ", new Date().getFullYear(), " A Whittle Wandering"] })] }), _jsxs("div", { className: "footer-section", children: [_jsx("h3", { children: "Follow the Journey" }), _jsxs("div", { className: "social-links", children: [_jsx("a", { href: "https://twitter.com/awhittlewander", target: "_blank", rel: "noopener noreferrer", children: "Twitter" }), _jsx("a", { href: "https://instagram.com/awhittlewandering", target: "_blank", rel: "noopener noreferrer", children: "Instagram" }), _jsx("a", { href: "https://youtube.com/awhittlewandering", target: "_blank", rel: "noopener noreferrer", children: "YouTube" })] })] }), _jsxs("div", { className: "footer-section", children: [_jsx("h3", { children: "Resources" }), _jsxs("ul", { children: [_jsx("li", { children: _jsx(Link, { to: "/about", children: "About the Trip" }) }), _jsx("li", { children: _jsx("a", { href: "https://www.tesla.com/supercharger", target: "_blank", rel: "noopener noreferrer", children: "Supercharger Network" }) }), _jsx("li", { children: _jsx("a", { href: "https://www.nps.gov/", target: "_blank", rel: "noopener noreferrer", children: "National Parks" }) })] })] })] }), _jsx("div", { className: "footer-bottom", children: _jsx("p", { children: "Powered by Cloudflare Workers | Built with \u2764\uFE0F in the USA" }) })] })] }));
}
