default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number
    build_app(
      scheme: "ContinentalUSA",
      export_method: "app-store"
    )
    upload_to_testflight(
      apple_id: ENV["APPLE_ID"],
      skip_waiting_for_build_processing: true
    )
  end

  desc "Push a new release build to the App Store"
  lane :release do
    increment_version_number
    increment_build_number
    build_app(
      scheme: "ContinentalUSA",
      export_method: "app-store"
    )
    upload_to_app_store(
      force: true,
      skip_metadata: true,
      skip_screenshots: true,
      skip_binary_upload: false
    )
  end
end
