name = "thewanderingwhittle-edge"
compatibility_date = "2025-05-31"
main = "src/index.ts"
[vars]
EDGE_HMAC_KEY = "48continental_secure_key"

[[kv_namespaces]]
binding = "APP_KV"
id = "8016b1e4a16f4fa7b75bcee9f1e37573"

[[kv_namespaces]]
binding = "ITINERARY_KV"
id = "41e8cca6911d47338647d950d2344d91"

[durable_objects]
bindings = [
  { name = "SYNC_SERVICE_DO", class_name = "SyncServiceDurableObject" }
]

[[migrations]]
tag = "v1"
new_classes = ["SyncServiceDurableObject"]
