name = "worker-name"
compatibility_date = "2025-05-31"
main = "src/index.ts"
[vars]
EDGE_HMAC_KEY = "${EDGE_HMAC_KEY}"
[[kv_namespaces]]
binding = "APP_KV"
id = "c7eba0c892bf4f2fbcf73fb60a38706c"
preview_id = "a68ee6412d644992b79b6fddd8d17f47"
